### ISSUE TITLE
Can't add cordova-screenshot plugin

### ISSUE THREAD

**Issue by truongthinnguyen** [gitawego/cordova-screenshot#53]
Hi,

I have a problem while installing this plugin.

```
$ cordova plugin add com.darktalker.cordova.screenshot
Fetching plugin "com.darktalker.cordova.screenshot" via cordova plugins registry

npm http GET http://registry.cordova.io/com.darktalker.cordova.screenshot
npm http 404 http://registry.cordova.io/com.darktalker.cordova.screenshot
Fetching from cordova plugins registry failed: 404 Not Found: com.darktalker.cor
dova.screenshot
Fetching plugin "com.darktalker.cordova.screenshot" via npm
npm http GET https://registry.npmjs.org/com.darktalker.cordova.screenshot
npm http 404 https://registry.npmjs.org/com.darktalker.cordova.screenshot
Fetching from npm failed: 404 Not Found: com.darktalker.cordova.screenshot
Error: 404 Not Found: com.darktalker.cordova.screenshot
    at RegClient.<anonymous> (c:\Users\DRAGON223\AppData\Roaming\npm\node_module
s\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\npm-registry-cl
ient\lib\request.js:268:14)
    at Request.self.callback (c:\Users\DRAGON223\AppData\Roaming\npm\node_module
s\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.j
s:148:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (c:\Users\DRAGON223\AppData\Roaming\npm\node_modules\
cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\index.js:
876:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (c:\Users\DRAGON223\AppData\Roaming\npm\node_
modules\cordova\node_modules\cordova-lib\node_modules\npm\node_modules\request\i
ndex.js:827:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
```

##### Installed platforms: android 4.0.2

What should I do to install this plugin?

Thank you,
Thin Nguyen

**Comment by gitawego** [comment]
it should work now.

**Comment by NewtonJoshua** [comment]
The same issue is happening again.

```
Error: Failed to fetch plugin git+https://github.com/gitawego/cordova-screenshot.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Failed to get absolute path to installed module
```

**Comment by ThiagoLovatine** [comment]
Yep, it's happening again... =/

**Comment by hoonblizz** [comment]
It's happening again!

**Comment by ThiagoLovatine** [comment]
That I did: Uninstalled node from brew and/or nvm, installed node from the website and it's working again.
